Others = {
    "PRODUCT_AVAILABILITY": ["ALTERNATIVE_PRODUCTS", "PRODUCT_QUERIES", "DISCOUNTS_AND_PROMOTIONS", "SHIPPING_TIMELINES", "OTHERS"],
    "DAMAGES": ["CLAIMS_AND_REFUND","DAMAGED_AFTER_DELIVERY","MISSING_ITEMS","OTHERS"],
    "ORDER_STATUS":["CANCELLATION","REFUND","ORDER_CONFIRMATION","ORDER_MODIFICATIONS","OTHERS"],
    "RETURNS":["REFUND","REPLACEMENT","RETURN_POLICY","QUERIES","SHIPPING_CHARGES_ADJUSTMENT","OTHERS"],
    "TRADE_APPLICATION":["DISCOUNTS_AND_PRICING","PROGRAM_BENEFITS_QUERIES","OTHERS"]
}
